# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: true
enable_free_tier: true
reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
  poem: true
  review_status: true
  fail_commit_status: true
  collapse_walkthrough: false
  finishing_touches:
    docstrings:
      enabled: false
    unit_tests:
      enabled: false
  pre_merge_checks:
    title:
      mode: "error"
      requirements: "Conventional Commits"
    description:
      mode: "off"
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - "master"
      - "develop"
    auto_incremental_review: true
  tools:
    eslint:
      enabled: true
chat:
  auto_reply: true
