sudo: false
language: node_js
node_js:
- '14'
install:
- npm run deploy
addons:
  ssh_known_hosts: vps514431.ovh.net
deploy:
- provider: script
  skip_cleanup: true
  script: bash ./deploy/deploy.sh
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_a9ed1542f049_key -iv $encrypted_a9ed1542f049_iv
  -in deploy/deploy_key.pem.enc -out deploy/deploy_key.pem -d
