sudo: false
language: node_js
node_js:
- '14'
install:
- npm run deploy
addons:
  ssh_known_hosts: vps-841374ca.vps.ovh.net
deploy:
- provider: script
  skip_cleanup: true
  script: bash ./deploy/deploy.sh
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_ae4bfc95fd3d_key -iv $encrypted_ae4bfc95fd3d_iv
  -in deploy/deploy-key.enc -out deploy/deploy-key -d
