sudo: false
language: node_js
node_js:
    - '10'
install:
    - npm run deploy
addons:
    ssh_known_hosts: vps514431.ovh.net
before_install:
    - openssl aes-256-cbc -K $encrypted_403adf0de49e_key -iv $encrypted_403adf0de49e_iv
        -in ./deploy/deploy_key.pem.enc -out ./deploy/deploy_key.pem -d
deploy:
    - provider: script
      skip_cleanup: true
      script: bash deploy.sh
      on:
          branch: master