runtime: nodejs20

handlers:
  - url: /(.*)
    static_files: .output/public/\1
    upload: .output/public/(.*)
    secure: always

  - url: /
    static_files: .output/public/index.html
    upload: .output/public/index.html
    secure: always