name: Mutant Tests 👽
description: Run Stryker mutant tests and upload reports.
author: Antoine ZANARDI

inputs:
  stryker-report-path:
    description: Path to Stryker HTML report
    required: true
    default: tests/stryker/coverage
  stryker-incremental-path:
    description: Path to Stryker incremental report
    required: true
    default: tests/stryker/incremental
  stryker-dashboard-api-key:
    description: Stryker Dashboard API key for authentication
    required: true

runs:
  using: composite
  steps:
    - name: Install project 📦
      uses: ./.github/actions/install-project

    - name: Mutant tests 👽
      id: mutant-tests
      shell: bash
      run: pnpm run test:stryker
      env:
        STRYKER_DASHBOARD_API_KEY: ${{ inputs.stryker-dashboard-api-key }}
        VERSION: ${{ github.head_ref || github.ref_name }}

    - name: Save stryker report as artifact 💎
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: stryker-html-report
        path: ${{ inputs.stryker-report-path }}/index.html
        if-no-files-found: ignore
        retention-days: 2

    - name: Save stryker incremental as artifact 💎
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: stryker-incremental-report
        path: ${{ inputs.stryker-incremental-path }}
        if-no-files-found: ignore
        retention-days: 2
