name: ⛵️ Deploy To Staging Workflow

on:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deployment:
    name: Deploy to Vercel ⛵
    permissions:
      contents: read
    runs-on: ubuntu-latest
    env:
      NUXT_PUBLIC_EMAIL: ${{ vars.NUXT_PUBLIC_EMAIL }}
      NUXT_PUBLIC_PHONE_NUMBER: ${{ vars.NUXT_PUBLIC_PHONE_NUMBER }}
      NUXT_PUBLIC_ADDRESS: ${{ vars.NUXT_PUBLIC_ADDRESS }}
      NUXT_SITE_NAME: ${{ vars.STAGING_SITE_NAME }}
      NUXT_SITE_URL: ${{ vars.STAGING_URL }}
    environment:
      name: Staging
      url: ${{ vars.STAGING_URL }}
    steps:
      - name: Checkout GitHub repository 📡
        uses: actions/checkout@v5

      - name: Install project dependencies 📦
        uses: ./.github/actions/install-project

      - name: Generate app ✨
        run: pnpm run generate

      - name: Deploy to Vercel ⛵
        id: deployment
        uses: amondnet/vercel-action@v41.1.4
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          vercel-args: --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
