name: 'SonarCloud Analysis 🌥️'
description: 'Run SonarCloud analysis with pnpm and Node.js setup.'
author: "Antoine ZANARDI"

inputs:
  UNIT_TESTS_COVERAGE_BASE_CACHE_KEY:
    description: 'Base cache key for unit tests coverage reports'
    required: true
  UNIT_TESTS_COVERAGE_REPORTS_PATH:
    description: 'Path to unit tests coverage reports'
    required: true
  SONARCLOUD_TOKEN:
    description: 'SonarCloud token for authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Compute safe branch name 🍃
      id: safe-branch-name
      uses: ./.github/actions/compute-safe-branch-name

    - name: Install pnpm 🏗️
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Restore pnpm dependencies from cache 🥡
      uses: actions/cache/restore@v4
      id: cache-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}

    - name: Restore tests coverage from cache 🥡
      uses: actions/cache/restore@v4
      id: cache-unit-tests-coverage
      with:
        path: ${{ inputs.UNIT_TESTS_COVERAGE_REPORTS_PATH }}
        key: ${{ inputs.UNIT_TESTS_COVERAGE_BASE_CACHE_KEY }}-${{ steps.safe-branch-name.outputs.safe-branch-name }}-
        restore-keys: |
          ${{ inputs.UNIT_TESTS_COVERAGE_BASE_CACHE_KEY }}-${{ steps.safe-branch-name.outputs.safe-branch-name }}-

    - name: SonarCloud Scan 🌥️
      uses: SonarSource/sonarqube-scan-action@v6.0.0
      env:
        SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
